### ISSUE TITLE
solve() fails on OS X 10.10.1

### ISSUE THREAD

**Issue by rleegates** [dpo/MUMPS.jl#1]
Dear MUMPS.jl developers,

I encountered a problem using MUMPS.jl on a fresh install of OS X 10.10.1 when trying the example in the README:

	julia> using MUMPS
	julia> ierr = mumps_initialize_mpi();
	MPI initialized with 1 processes
	julia> A = sprand(10, 10, .2) + speye(10);
	julia> rhs = rand(10);
	julia> x = solve(A, rhs);	
	all kinds of MUMPS output...

	 GLOBAL TIME FOR MATRIX DISTRIBUTION       =      0.0001
	 ** Memory relaxation parameter ( ICNTL(14)  )            :        20
	 ** Rank of processor needing largest memory in facto     :         0
	 ** Space in MBYTES used by this processor for facto      :         1
	 ** Avg. Space in MBYTES per working proc during facto    :         1
	dyld: lazy symbol binding failed: Symbol not found: _idamax_
	  Referenced from: /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/lib/libdmumps.dylib
	  Expected in: flat namespace
	
	dyld: Symbol not found: _idamax_
	  Referenced from: /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/lib/libdmumps.dylib
	  Expected in: flat namespace
	
	Trace/BPT trap: 5

This used to work fine on OS X 10.9. MUMPS was built using

brew install mumps --with-mpi --with-scotch5 --with-openblas

Best regards,

Robert

**Comment by rleegates** [comment]
Great :+1: Thank you very much for your effort! Please give me a quick heads up when it's ready. By the way, your package collides with a package of the same name. How about a rename?

**Comment by dpo** [comment]
The last few commits should fix your problem. It would be great if you could test. Which one is the other package? [This one](https://github.com/lruthotto/MUMPS.jl)?

**Comment by rleegates** [comment]
Okay, I'll test it in one or two hours. Yup, that's the one.

**Comment by rleegates** [comment]
Didn't work, but maybe I did something wrong. Here's what I did (sorry for the full cut & paste, but I guess you'd like to know all output):

	julia> Pkg.rm("MUMPS")
	INFO: Removing MUMPS (unregistered)

	julia> exit()
	Coruscant:~ rgates$ brew uninstall MUMPS
	Uninstalling /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/mumps/4.10.0_2...
	Coruscant:~ rgates$ brew install mumps --with-mpi --with-scotch5 --with-openblas
	==> Installing mumps from homebrew/homebrew-science
	==> Using Homebrew-provided fortran compiler.
	This may be changed by setting the FC environment variable.
	==> Building with an alternative Fortran compiler
	This is unsupported.
	Warning: No Fortran optimization information was provided.  You may want to consider
	setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
	`brew install` if your compiler is compatible with GCC.
	
	If you like the default optimization level of your compiler, ignore this
	warning.
	==> Building with an alternative Fortran compiler
	This is unsupported.
	Warning: No Fortran optimization information was provided.  You may want to consider
	setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
	`brew install` if your compiler is compatible with GCC.
	
	If you like the default optimization level of your compiler, ignore this
	warning.
	==> Downloading http://mumps.enseeiht.fr/MUMPS_4.10.0.tar.gz
	Already downloaded: /Library/Caches/Homebrew/mumps-4.10.0.tar.gz
	==> Patching
	==> make all LIBEXT=.dylib AR=$(FL) -shared -Wl,-install_name -Wl,/Volumes/rgate
	🍺  /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/mumps/4.10.0_2: 39 files, 8.1M, built in 2.2 minutes
	Coruscant:~ rgates$ julia
	julia> Pkg.clone("https://github.com/dpo/MUMPS.jl.git")
	INFO: Cloning MUMPS from https://github.com/dpo/MUMPS.jl.git
	INFO: Computing changes...
	WARNING: unknown MUMPS commit d48515f3, metadata may be ahead of package cache
	INFO: Cloning cache of MPI from git://github.com/JuliaParallel/MPI.jl.git
	INFO: Installing MPI v0.2.5
	INFO: Building MPI
	INFO: Attempting to Create directory /Volumes/rgates/.julia/v0.3/MPI/deps/build
	INFO: Changing Directory to /Volumes/rgates/.julia/v0.3/MPI/deps/build
	-- The Fortran compiler identification is GNU
	-- The C compiler identification is AppleClang 6.0.0.6000056
	-- Check for working Fortran compiler: /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/bin/gfortran
	-- Check for working Fortran compiler: /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/bin/gfortran  -- works
	-- Detecting Fortran compiler ABI info
	-- Detecting Fortran compiler ABI info - done
	-- Checking whether /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/bin/gfortran supports Fortran 90
	-- Checking whether /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/bin/gfortran supports Fortran 90 -- yes
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Found Git: /Applications/Julia.app/Contents/Resources/julia/libexec/git-core/git (found version "1.8.5.6") 
	-- Found MPI_C: /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/open-mpi/1.8.4/lib/libmpi.dylib  
	-- Found MPI_Fortran: /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/open-mpi/1.8.4/lib/libmpi_usempif08.dylib;/Volumes/rgates/.julia	/v0.3/Homebrew/deps/usr/Cellar/open-mpi/1.8.4/lib/libmpi_usempi_ignore_tkr.a;/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/open-	mpi/1.8.4/lib/libmpi_mpifh.dylib;/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/open-mpi/1.8.4/lib/libmpi.dylib  
	-- Detecting Fortran/C Interface
	-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
	CMake Warning (dev) at CMakeLists.txt:31 (file):
	  Policy CMP0053 is not set: Simplify variable reference and escape sequence
	  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
	  cmake_policy command to set the policy and suppress this warning.
	
	  For input:
	
	    '\#define INSTALL \"@CMAKE_INSTALL_PREFIX@\"\n'
	
	  the old evaluation rules produce:
	
	    '#define INSTALL "/Volumes/rgates/.julia/v0.3/MPI/deps/src"
	    '
	
	  but the new evaluation rules produce:
	
	    '#define INSTALL "@CMAKE_INSTALL_PREFIX@"
	    '
	
	  Using the old result for compatibility since the policy is not set.
	This warning is for project developers.  Use -Wno-dev to suppress it.
	
	-- Configuring done
	CMake Warning (dev):
	  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
	  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
	  set the policy and suppress this warning.
	
	  MACOSX_RPATH is not specified for the following targets:
	
	   juliampi
	
	This warning is for project developers.  Use -Wno-dev to suppress it.
	
	-- Generating done
	-- Build files have been written to: /Volumes/rgates/.julia/v0.3/MPI/deps/build
	Scanning dependencies of target make_f_const
	[ 20%] Building Fortran object CMakeFiles/make_f_const.dir/make_f_const.f.o
	Linking Fortran executable make_f_const
	[ 20%] Built target make_f_const
	Scanning dependencies of target version
	[ 20%] Built target version
	Scanning dependencies of target make_f2c
	[ 40%] Building C object CMakeFiles/make_f2c.dir/make_f2c.c.o
	Linking C executable make_f2c
	[ 40%] Built target make_f2c
	Scanning dependencies of target mpijl
	[ 60%] Generating compile-time.jl
	[ 60%] Built target mpijl
	Scanning dependencies of target mpijl-build
	[ 80%] Generating mpi-build.jl
	[ 80%] Built target mpijl-build
	Scanning dependencies of target juliampi
	[100%] Building Fortran object CMakeFiles/juliampi.dir/mpi.f.o
	Linking Fortran shared library libjuliampi.dylib
	[100%] Built target juliampi
	[ 20%] Built target make_f_const
	[ 20%] Built target version
	[ 40%] Built target make_f2c
	[ 60%] Built target mpijl
	[ 80%] Built target mpijl-build
	[100%] Built target juliampi
	Install the project...
	-- Install configuration: ""
	-- Installing: /Volumes/rgates/.julia/v0.3/MPI/deps/src/./compile-time.jl
	-- Installing: /Volumes/rgates/.julia/v0.3/MPI/deps/usr/lib/libjuliampi.dylib
	Running tests...
	Test project /Volumes/rgates/.julia/v0.3/MPI/deps/build
	    Start 1: test_bcast.jl_np:2
	1/6 Test #1: test_bcast.jl_np:2 ...............   Passed    2.79 sec
	    Start 2: test_reduce.jl_np:2
	2/6 Test #2: test_reduce.jl_np:2 ..............   Passed    1.50 sec
	    Start 3: test_sendrecv.jl_np:2
	3/6 Test #3: test_sendrecv.jl_np:2 ............   Passed    1.73 sec
	    Start 4: test_bcast.jl_np:5
	4/6 Test #4: test_bcast.jl_np:5 ...............   Passed    3.03 sec
	    Start 5: test_reduce.jl_np:5
	5/6 Test #5: test_reduce.jl_np:5 ..............   Passed    1.85 sec
	    Start 6: test_sendrecv.jl_np:5
	6/6 Test #6: test_sendrecv.jl_np:5 ............   Passed    2.61 sec
	
	100% tests passed, 0 tests failed out of 6
	
	Total Test time (real) =  13.51 sec
	INFO: Package database updated
	
	julia> Pkg.build("MUMPS")
	INFO: Building MPI
	INFO: Building MUMPS
	clang -g -c  -I/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/opt/mumps/include  -I/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/opt/open-	mpi/include -fPIC jmumps.c
	libtool -dynamic -undefined dynamic_lookup -macosx_version_min 10.8 jmumps.o -o /Volumes/rgates/.julia/v0.3/MUMPS/src/libjmumps.dylib -	install_name /Volumes/rgates/.julia/v0.3/MUMPS/src/libjmumps.dylib -L/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/opt/mumps/lib -ldmumps -	lzmumps -lmumps_common -lpord -L/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/opt/scotch5/lib -lptesmumps -lptscotch -lptscotcherr -L/	Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/opt/open-mpi/lib -lmpi -lmpi_mpifh
	
	julia> using MUMPS
	
	julia> using MPI
	
	julia> MPI.Init()
	
	julia> A = sprand(10, 10, .2) + speye(10); rhs = rand(10);
	
	julia> x = solve(A, rhs);
	Entering DMUMPS driver with JOB, N, NZ =   4          10             32
	
	 DMUMPS 4.10.0        
	L U Solver for unsymmetric matrices
	Type of parallelism: Working host
	
	 ****** ANALYSIS STEP ********
	
	 Resetting candidate strategy to 0 because NSLAVES=1
	 
	 ... Structural symmetry (in percent)=   50
	 Density: NBdense, Average, Median   =    0    4    3
	 ... No column permutation
	 Ordering based on AMF 
	
	Leaving analysis phase with  ...
	INFOG(1)                                       =               0
	INFOG(2)                                       =               0
	 -- (20) Number of entries in factors (estim.) =              58
	 --  (3) Storage of factors  (REAL, estimated) =              58
	 --  (4) Storage of factors  (INT , estimated) =             140
	 --  (5) Maximum frontal size      (estimated) =               4
	 --  (6) Number of nodes in the tree           =               7
	 -- (32) Type of analysis effectively used     =               1
	 --  (7) Ordering option effectively used      =               2
	ICNTL(6) Maximum transversal option            =               0
	ICNTL(7) Pivot order option                    =               7
	Percentage of memory relaxation (effective)    =              20
	Number of level 2 nodes                        =               0
	Number of split nodes                          =               0
	RINFOG(1) Operations during elimination (estim)=   1.600D+02
	 ** Rank of proc needing largest memory in IC facto        :         0
	 ** Estimated corresponding MBYTES for IC facto            :         1
	 ** Estimated avg. MBYTES per work. proc at facto (IC)     :         1
	 ** TOTAL     space in MBYTES for IC factorization         :         1
	 ** Rank of proc needing largest memory for OOC facto      :         0
	 ** Estimated corresponding MBYTES for OOC facto           :         1
	 ** Estimated avg. MBYTES per work. proc at facto (OOC)    :         1
	 ** TOTAL     space in MBYTES for OOC factorization        :         1
	
	 ****** FACTORIZATION STEP ********
	
	
	 GLOBAL STATISTICS PRIOR NUMERICAL FACTORIZATION ...
	 NUMBER OF WORKING PROCESSES              =           1
	 OUT-OF-CORE OPTION (ICNTL(22))           =           0
	 REAL SPACE FOR FACTORS                   =          58
	 INTEGER SPACE FOR FACTORS                =         140
	 MAXIMUM FRONTAL SIZE (ESTIMATED)         =           4
	 NUMBER OF NODES IN THE TREE              =           7
	 Convergence error after scaling for ONE-NORM (option 7/8)   = 0.33D+00
	 Maximum effective relaxed size of S              =         226
	 Average effective relaxed size of S              =         226
	 GLOBAL TIME FOR MATRIX DISTRIBUTION       =      0.0001
	 ** Memory relaxation parameter ( ICNTL(14)  )            :        20
	 ** Rank of processor needing largest memory in facto     :         0
	 ** Space in MBYTES used by this processor for facto      :         1
	 ** Avg. Space in MBYTES per working proc during facto    :         1
	dyld: lazy symbol binding failed: Symbol not found: _idamax_
	  Referenced from: /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/lib/libdmumps.dylib
	  Expected in: flat namespace
	
	dyld: Symbol not found: _idamax_
	  Referenced from: /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/lib/libdmumps.dylib
	  Expected in: flat namespace
	
	Trace/BPT trap: 5

**Comment by dpo** [comment]
Thanks for the detailed output. Alternatively, you can put all that in a gist to keep the discussion airy. I forgot that you were using OpenBLAS. I just pushed an update. Remember that you can `Pkg.test("MUMPS")` and a script very similar to the example is in `examples/mumps_mpi.jl`.

I phased out the simplistic MPI interface in favor of `MPI.jl` which allows much finer-grained control.

**Comment by rleegates** [comment]
When installing without openblas, I get:
	Coruscant:~ rgates$ brew test mumps
	Testing mumps
	==> mpirun -np 2 /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/mumps/4.10.0_2/share/mumps/examples/ssimpletest < /Volumes
	#1  0x10a5a4cae
	#2  0x7fff8c23af19
	--------------------------------------------------------------------------
	mpirun noticed that process rank 1 with PID 9971 on node Coruscant exited on signal 11 (Segmentation fault: 11).
	--------------------------------------------------------------------------
	Error: mumps: failed
	Failed executing: mpirun -np 2 /Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/mumps/4.10.0_2/share/mumps/examples/ssimpletest < /	Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/mumps/4.10.0_2/share/mumps/examples/input_simpletest_real 
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Homebrew/formula.rb:691:in `system'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-science/mumps.rb:113:in `block in <class:Mumps>'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Homebrew/formula.rb:609:in `block in run_test'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Homebrew/formula.rb:607:in `run_test'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Homebrew/cmd/test.rb:59:in `block (2 levels) in test'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Homebrew/cmd/test.rb:58:in `block in test'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Homebrew/cmd/test.rb:37:in `each'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/Homebrew/cmd/test.rb:37:in `test'
	/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Library/brew.rb:136:in `<main>'

**Comment by dpo** [comment]
Hold on, your MUMPS install is in `~/.julia`. It looks like you're using the MUMPS build with the other `MUMPS.jl` package, and not the real Homebrew MUMPS. Would you mind removing the other `MUMPS.jl` and making sure Homebrew MUMPS is installed correctly? I have to sort out the `MUMPS.jl` stuff with Lars.

**Comment by rleegates** [comment]
Are you sure? Homebrew exited with:
/Volumes/rgates/.julia/v0.3/Homebrew/deps/usr/Cellar/mumps/4.10.0_2: 39 files, 8.1M, built in 2.5 minutes

**Comment by dpo** [comment]
It seems you're using `HOMEBREW.jl`. Are you not using the standard Homebrew at all?

**Comment by rleegates** [comment]
This is Homebrew, downloaded from http://brew.sh a few days ago, standard install, no configuration change, and installing MUMPS via OSX's Terminal using the commands supplied in the README.md. I do wonder why it chooses to install in .julia, however, that just happens automatically.

**Comment by dpo** [comment]
You have two versions of Homebrew installed. I do too and that's fine, but when you use `brew` in the terminal, it shouldn't default to `HOMEBREW.jl`. I *think* that one is only intended to be used from Julia. I'm a bit uneasy that that's the one managing all your packages. When I do `which brew`, my system says `/usr/local/bin/brew`, not `~/.julia/v0.3/Homebrew/deps/usr/bin/brew`. How about you?

**Comment by rleegates** [comment]
Yes, I'm sorry, I must have done something weird when installing. "brew test mumps" works fine now, however, when doing Pkg.test("MUMPS"), the package doesn't seem to find the shared library libjmumps.dylib. When checking for LD path:

	Coruscant:src rgates$ echo $LD_LIBRARY_PATH
	~/.julia/v0.3/MUMPS/src:

and ls'ing in that directory

	Coruscant:src rgates$ ls ~/.julia/v0.3/MUMPS/src
	Makefile	jmumps.c	jmumps.h	jmumps.o	libjmumps.dylib	mumps.jl

It's there alright...

**Comment by dpo** [comment]
Is that Julia prompt in the same terminal where you set `LD_LIBRARY_PATH`, or in a terminal where that variable was set correctly? You can check with `ENV["LD_LIBRARY_PATH"]` at the Julia prompt.

**Comment by rleegates** [comment]
I knew that question was coming :D (LD... is in .profile). Here's the workflow:

	julia> ENV["LD_LIBRARY_PATH"]
	"~/.julia/v0.3/MUMPS/src:"
	
	julia> Pkg.test("MUMPS")
	INFO: Testing MUMPS
	ERROR: error compiling __Mumps#5__: could not load module libjmumps: dlopen(libjmumps.dylib, 1): image not found
	 in include at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
	 in include_from_node1 at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
	 in include at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
	 in include_from_node1 at loading.jl:128
	 in process_options at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
	 in _start at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
	while loading /Volumes/rgates/.julia/v0.3/MUMPS/test/mumps_test.jl, in expression starting on line 18
	while loading /Volumes/rgates/.julia/v0.3/MUMPS/test/runtests.jl, in expression starting on line 1
	
	================================[ ERROR: MUMPS ]================================
	
	failed process: Process(`/Applications/Julia.app/Contents/Resources/julia/bin/julia /Volumes/rgates/.julia/v0.3/MUMPS/test/runtests.jl`, 	ProcessExited(1)) [1]
	
	================================================================================
	WARNING: unknown MUMPS commit d48515f3, metadata may be ahead of package cache
	INFO: No packages to install, update or remove
	ERROR: MUMPS had test errors
	 in error at error.jl:21
	 in test at pkg/entry.jl:718
	 in anonymous at pkg/dir.jl:28
	 in cd at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
	 in cd at pkg/dir.jl:28
	 in test at pkg.jl:67
	
	julia>

**Comment by rleegates** [comment]
Okay, I just tried writing the whole path in .profile. Awkwardly, that worked... Here we go with the new error:

	julia> ENV["LD_LIBRARY_PATH"]
	"/Volumes/rgates/.julia/v0.3/MUMPS/src:"
	
	julia> Pkg.test("MUMPS")
	INFO: Testing MUMPS
	Entering DMUMPS driver with JOB, N, NZ =   4           4              4
	
	 DMUMPS 4.10.0        
	L D L^T Solver for symmetric positive definite matrices
	Type of parallelism: Working host
	
	 ****** ANALYSIS STEP ********
	
	 ....
	
	 ****** FACTORIZATION STEP ********
	
	
	 .....
	
	 ****** SOLVE & CHECK STEP ********
	
	
	 STATISTICS PRIOR SOLVE PHASE     ...........
	 NUMBER OF RIGHT-HAND-SIDES                    =           1
	 BLOCKING FACTOR FOR MULTIPLE RHS              =           1
	 ICNTL (9)                                     =           1
	  --- (10)                                     =           0
	  --- (11)                                     =           0
	  --- (20)                                     =           0
	  --- (21)                                     =           0
	  --- (30)                                     =           0
	dyld: lazy symbol binding failed: Symbol not found: _dtrsv_
	  Referenced from: /usr/local/lib/libdmumps.dylib
	  Expected in: flat namespace
	
	dyld: Symbol not found: _dtrsv_
	  Referenced from: /usr/local/lib/libdmumps.dylib
	  Expected in: flat namespace
	
	================================[ ERROR: MUMPS ]================================
	
	failed process: Process(`/Applications/Julia.app/Contents/Resources/julia/bin/julia /Volumes/rgates/.julia/v0.3/MUMPS/test/runtests.jl`, 	ProcessSignaled(5)) [0]
	
	================================================================================
	WARNING: unknown MUMPS commit d48515f3, metadata may be ahead of package cache
	INFO: No packages to install, update or remove
	ERROR: MUMPS had test errors
	 in error at error.jl:21
	 in test at pkg/entry.jl:718
	 in anonymous at pkg/dir.jl:28
	 in cd at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib
	 in cd at pkg/dir.jl:28
	 in test at pkg.jl:67

**Comment by dpo** [comment]
Sorry for the treasure hunt! That error's related to OpenBLAS. Two questions:

1. What does this say for you:
````
otool -L ~/.julia/v0.3/MUMPS/src/libjmumps.dylib
````
2. What does this say for you:
````
nm $(brew --prefix openblas)/lib/libopenblas.dylib | grep dtrsv
````

**Comment by rleegates** [comment]
No problem :) I owe more thanks to you, I guess!

	Coruscant:~ rgates$ otool -L ~/.julia/v0.3/MUMPS/src/libjmumps.dylib
	/Volumes/rgates/.julia/v0.3/MUMPS/src/libjmumps.dylib:
		/Volumes/rgates/.julia/v0.3/MUMPS/src/libjmumps.dylib (compatibility version 0.0.0, current version 0.0.0)
		/usr/local/lib/libdmumps.dylib (compatibility version 0.0.0, current version 0.0.0)
		/usr/local/lib/libzmumps.dylib (compatibility version 0.0.0, current version 0.0.0)
		/usr/local/lib/libmumps_common.dylib (compatibility version 0.0.0, current version 0.0.0)
		/usr/local/lib/libpord.dylib (compatibility version 0.0.0, current version 0.0.0)
		/usr/local/opt/scotch5/lib/libesmumps.dylib (compatibility version 0.0.0, current version 0.0.0)
		/usr/local/opt/scotch5/lib/libptscotch.dylib (compatibility version 0.0.0, current version 0.0.0)
		/usr/local/opt/scotch5/lib/libptscotcherr.dylib (compatibility version 0.0.0, current version 0.0.0)
		/usr/local/lib/libmpi.1.dylib (compatibility version 8.0.0, current version 8.0.0)
		/usr/local/lib/libmpi_mpifh.2.dylib (compatibility version 8.0.0, current version 8.0.0)
	Coruscant:~ rgates$ nm $(brew --prefix openblas)/lib/libopenblas.dylib | grep dtrsv
	error: /Library/Developer/CommandLineTools/usr/bin/nm: can't open file: /usr/local/Cellar/openblas/0.2.13/lib/libopenblas.dylib (No such 	file or directory)

I guess the latter error is due to the fact that mumps wasn't installed with the openblas option?!

**Comment by dpo** [comment]
That's alright. The Julia interface correctly left OpenBLAS out of the picture. I just pushed a minor change to the Makefile. Would you mind updating and rebuilding the Julia wrapper?

**Comment by rleegates** [comment]
Perfect! Thank you so much!

Any chance that we can silence the MUMPS printout? Hate to have it clutter my output :)

**Comment by dpo** [comment]
Pleasure. When I fixed the MUMPS segfault, I made linking with MUMPS more complicated. Now I have to fix *that*.

You can silence MUMPS in two ways:
* Use the convenience constructor and pass `verbose=false` (which is the default), e.g.,
````
mumps = Mumps(sym=mumps_definite, verbose=false);
````
* Use the integer parameter array, e.g.,
````
icntl = default_icntl;
icntl[1:4] = 0;  # Or whatever you want.
````
See [here](https://github.com/dpo/MUMPS.jl/blob/master/src/mumps.jl#L22) for the components of the integer parameters.
